AWSTemplateFormatVersion: '2010-09-09'
Description: Template to deploy resources for Vectra's AWS entity remediation solution.

Parameters:
  VectraRemediationLambdaName:
    Type: String
    Description: 'Name assigned to Vectra remediation AWS Lambda function'
    Default: 'vectra-remediation-function'
  VectraRemediationSnsTopic:
    Type: String
    Description: 'Name assigned to Vectra remediation AWS SNS topic'
    Default: 'vectra-remediation-sns-topic'
  VectraRemediationAuditSnsTopic:
    Type: String
    Description: 'Name assigned to Vectra remediation audit AWS SNS topic'
    Default: 'vectra-remediation-audit-sns-topic'
  VectraRemediationFailureSnsTopic:
    Type: String
    Description: 'Name assigned to Vectra remediation failure AWS SNS topic'
    Default: 'vectra-remediation-failure-sns-topic'
  SnsMessageExternalID:
    Type: String
    MinLength: 9
    Description: 'Extrenal ID to validate remediation SNS message. 9 characters long'
  VectraRemediationAuditSnsTopicSubscriptionEmail:
    Type: String
    AllowedPattern: '[^@]+@[^@]+\.[^@]+'
    Description: 'Email address to receive remediation notifications'
  VectraRemediationFailureSnsTopicSubscriptionEmail:
    Type: String
    AllowedPattern: '[^@]+@[^@]+\.[^@]+'
    Description: 'Email address to receive remediation failure notifications'
Resources:
    RemediationTopic:
        Type: 'AWS::SNS::Topic'
        Properties:
            DisplayName: !Sub 'Vectra Entity Remediation Topic'
            TopicName: !Ref VectraRemediationSnsTopic
            Subscription:
                - Protocol: lambda
                  Endpoint: !GetAtt RemediationLambda.Arn
    RemediationAuditTopic:
        Type: 'AWS::SNS::Topic'
        Properties:
            DisplayName: !Sub 'Vectra Entity Remediation Audit'
            TopicName: !Ref VectraRemediationAuditSnsTopic
    RemediationFailureTopic:
        Type: 'AWS::SNS::Topic'
        Properties:
            DisplayName: !Sub 'Vectra Entity Remediation Failure'
            TopicName: !Ref VectraRemediationFailureSnsTopic
    RemediationAuditTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: !Ref VectraRemediationAuditSnsTopicSubscriptionEmail
        Protocol: email
        TopicArn: !Ref 'RemediationAuditTopic'
    RemediationFailureTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: !Ref VectraRemediationFailureSnsTopicSubscriptionEmail
        Protocol: email
        TopicArn: !Ref 'RemediationFailureTopic'
    RemediationLambdaInvokePermission:
        Type: 'AWS::Lambda::Permission'
        Properties:
          Action: 'lambda:InvokeFunction'
          FunctionName: !Ref RemediationLambda
          Principal: sns.amazonaws.com
    RemediationTopicPolicy:
        Type: 'AWS::SNS::TopicPolicy'
        Properties:
            Topics:
                - !Ref RemediationTopic
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Action: 'sns:Publish'
                  Resource: !Ref RemediationTopic
                  Principal:
                    AWS: '*'
                  Condition:
                    ArnLike:
                        AWS:SourceArn: !Sub 'arn:aws:*:*:${AWS::AccountId}:*'
    RemediationLambdaExecutionRole:
        Type: 'AWS::IAM::Role'
        Properties:
            RoleName: 'VectraRemediationLambdaExecutionRole'
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                          - lambda.amazonaws.com
                      Action:
                        - sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Policies:
              - PolicyName: VectraRolePolicyForRemediationLambda
                PolicyDocument: 
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                         - sts:AssumeRole
                        Resource: '*'
                      - Effect: Allow
                        Action:
                          - sns:Publish
                        Resource: 
                          - !Sub ${RemediationAuditTopic.TopicArn}
                          - !Sub ${RemediationFailureTopic.TopicArn}
    RemediationAuditTopicPolicy:
        Type: 'AWS::SNS::TopicPolicy'
        Properties:
            Topics:
                - !Ref RemediationAuditTopic
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Action: 'sns:Publish'
                  Resource: !Ref RemediationAuditTopic
                  Principal:
                    Service: lambda.amazonaws.com
                  Condition:
                    ArnLike:
                        AWS:SourceArn: !Sub ${RemediationLambdaExecutionRole.Arn}
    RemediationFailureTopicPolicy:
        Type: 'AWS::SNS::TopicPolicy'
        Properties:
            Topics:
                - !Ref RemediationFailureTopic
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Action: 'sns:Publish'
                  Resource: !Ref RemediationFailureTopic
                  Principal:
                    Service: lambda.amazonaws.com
                  Condition:
                    ArnLike:
                        AWS:SourceArn: !Sub ${RemediationLambdaExecutionRole.Arn}
    RemediationLambda:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: !Ref VectraRemediationLambdaName
            Handler: lambda_function.lambda_handler
            Runtime: python3.9
            Role: !Sub ${RemediationLambdaExecutionRole.Arn}
            Code:
                S3Bucket: "dev-remediation"
                S3Key: "remediation_lambda_handler.zip"
            Description: ''
            MemorySize: 128
            Timeout: 120
            Environment:
              Variables:
                SNSMessageExternalId: !Ref SnsMessageExternalID
                VectraRoleForRemediationLambda: 'VectraRoleForRemediationLambdaFunction'
                VectraAuditRemediationSnsTopic:  !GetAtt RemediationAuditTopic.TopicArn
            DeadLetterConfig:
              TargetArn: !GetAtt RemediationFailureTopic.TopicArn
    VectraRoleForRemediationLambda:
        Type: 'AWS::IAM::Role'
        Properties:
            RoleName: 'VectraRoleForRemediationLambdaFunction'
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                        AWS:
                          - !Sub ${RemediationLambdaExecutionRole.Arn}
                      Action:
                        - sts:AssumeRole
            Policies:
              - PolicyName: VectraRolePolicyForEntityRemediationLambdaFunction
                PolicyDocument: 
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                          - ec2:AuthorizeSecurityGroupEgress 
                          - ec2:AuthorizeSecurityGroupIngress 
                          - ec2:RevokeSecurityGroupIngress 
                          - ec2:RevokeSecurityGroupEgress 
                          - ec2:DisassociateIamInstanceProfile 
                          - lambda:GetFunctionConfiguration 
                          - lambda:PutFunctionConcurrency
                        Resource: 
                          - !Sub "arn:aws:lambda:*:${AWS::AccountId}:function:*"
                          - !Sub "arn:aws:ec2:*:${AWS::AccountId}:security-group/*"
                          - !Sub "arn:aws:ec2:*:${AWS::AccountId}:security-group-rule/*"
                          - !Sub "arn:aws:ec2:*:${AWS::AccountId}:instance/*"
                      - Effect: Allow
                        Action: 
                          - ec2:DescribeInstances 
                          - ec2:DescribeIamInstanceProfileAssociations 
                          - ec2:CreateSecurityGroup 
                          - ec2:ModifyInstanceAttribute 
                          - ec2:DescribeSecurityGroups
                        Resource: '*'
                      - Effect: Allow
                        Action:
                          - iam:AttachUserPolicy
                          - iam:AttachRolePolicy
                        Resource:
                          - !Sub "arn:aws:iam::${AWS::AccountId}:role/*"
                          - !Sub "arn:aws:iam::${AWS::AccountId}:user/*"
Outputs:
  RemediationTopicName:
    Description: The Vectra remediation SNS topic name
    Value: !GetAtt RemediationTopic.TopicName
  RemediationLambdaName:
    Description: The Vectra remediation Lambda function name
    Value: !Ref VectraRemediationLambdaName
  RemediationLambdaExecutionRoleArn:
    Description: The Vectra remediation Lambda execution role arn
    Value: !GetAtt RemediationLambdaExecutionRole.Arn
  RemediationAuditRemediationSnsTopicName:
    Description: The Vectra remediation audit SNS topic name
    Value: !GetAtt RemediationAuditTopic.TopicName
  RemediationAuditRemediationSnsTopicName:
    Description: The Vectra remediation failure SNS topic name
    Value: !GetAtt RemediationFailureTopic.TopicName
  VectraRoleForRemediationLambdaName:
    Description: The Vectra IAM Role assumed by Remediation Lambda 
    Value: 'VectraRoleForRemediationLambdaFunction'