AWSTemplateFormatVersion: '2010-09-09'
Description: Template to deploy resources for Vectra's AWS entity remediation solution.

Parameters:
  VectraRemediationLambdaNameParameter:
    Type: String
    Description: 'Name assigned to Vectra remediation AWS Lambda function'
    Default: 'vectra-remediation-function'
  VectraRemediationSnsTopicParameter:
    Type: String
    Description: 'Name assigned to Vectra remediation AWS SNS topic'
    Default: 'vectra-remediation-sns-topic'
  VectraRemediationAuditSnsTopicParameter:
    Type: String
    Description: 'Name assigned to Vectra remediation audit AWS SNS topic'
    Default: 'vectra-remediation-audit-sns-topic'
  SnsMessageExternalIDParameter:
    Type: String
    MinLength: 9
    Description: 'Extrenal ID to validate remediation SNS message. 9 characters long'
  VectraRemediationAuditSnsTopicSubscriptionEmailParameter:
    Type: String
    AllowedPattern: '[^@]+@[^@]+\.[^@]+'
    Description: 'Email address to receive remediation notifications'
Resources:
    RemediationTopic:
        Type: 'AWS::SNS::Topic'
        Properties:
            DisplayName: !Sub 'Vectra Entity Remediation Topic'
            TopicName: !Ref VectraRemediationSnsTopicParameter
            Subscription:
                - Protocol: lambda
                  Endpoint: !GetAtt RemediationLambda.Arn
    RemediationAuditTopic:
        Type: 'AWS::SNS::Topic'
        Properties:
            DisplayName: !Sub 'Vectra Entity Remediation Audit Topic'
            TopicName: !Ref VectraRemediationAuditSnsTopicParameter
    RemediationAuditTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: !Ref VectraRemediationAuditSnsTopicSubscriptionEmailParameter
        Protocol: email
        TopicArn: !Ref 'RemediationAuditTopic'
    RemediationLambdaInvokePermission:
        Type: 'AWS::Lambda::Permission'
        Properties:
          Action: 'lambda:InvokeFunction'
          FunctionName: !Ref RemediationLambda
          Principal: sns.amazonaws.com
    RemediationTopicPolicy:
        Type: 'AWS::SNS::TopicPolicy'
        Properties:
            Topics:
                - !Ref RemediationTopic
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Action: 'sns:Publish'
                  Resource: !Ref RemediationTopic
                  Principal:
                    AWS: '*'
                  Condition:
                    ArnLike:
                        AWS:SourceArn: !Sub 'arn:aws:*:*:${AWS::AccountId}:*'
    RemediationLambdaExecutionRole:
        Type: 'AWS::IAM::Role'
        Properties:
            RoleName: 'VectraRemediationLambdaExecutionRole'
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                          - lambda.amazonaws.com
                      Action:
                        - sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Policies:
              - PolicyName: VectraRolePolicyForRemediationLambda
                PolicyDocument: 
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                         - sts:AssumeRole
                        Resource: '*'
                      - Effect: Allow
                        Action:
                          - sns:Publish
                        Resource: !Sub ${RemediationAuditTopic.TopicArn}
    RemediationAuditTopicPolicy:
        Type: 'AWS::SNS::TopicPolicy'
        Properties:
            Topics:
                - !Ref RemediationAuditTopic
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Action: 'sns:Publish'
                  Resource: !Ref RemediationTopic
                  Principal:
                    Service: lambda.amazonaws.com
                  Condition:
                    ArnLike:
                        AWS:SourceArn: !Sub ${RemediationLambdaExecutionRole.Arn}
    RemediationLambda:
        Type: 'AWS::Lambda::Function'
        Properties:
            FunctionName: !Ref VectraRemediationLambdaNameParameter
            Handler: lambda_function.lambda_handler
            Runtime: python3.9
            Role: !Sub ${RemediationLambdaExecutionRole.Arn}
            Code:
                S3Bucket: "dev-remediation"
                S3Key: "remediation_lambda_handler.zip"
            Description: ''
            MemorySize: 128
            Timeout: 60
            Environment:
              Variables:
                SNSMessageExternalId: !Ref SnsMessageExternalIDParameter
                VectraRoleForRemediationLambda: 'VectraRoleForRemediationLambdaFunction'
                VectraAuditRemediationSnsTopic:  !GetAtt RemediationAuditTopic.TopicArn
    

Outputs:
  RemediationTopicName:
    Description: The Vectra remediation SNS topic name
    Value: !GetAtt RemediationTopic.TopicName
  RemediationLambdaName:
    Description: The Vectra remediation Lambda function name
    Value: !Ref VectraRemediationLambdaNameParameter
  RemediationLambdaExecutionRoleArn:
    Description: The Vectra remediation Lambda execution role arn
    Value: !GetAtt RemediationLambdaExecutionRole.Arn
  RemediationAuditRemediationSnsTopicName:
    Description: The Vectra remediation audit SNS topic name
    Value: !GetAtt RemediationAuditTopic.TopicName